apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ze-prod
resources:
  - namespace.yaml
  - ../../base
  - networkpolicy.yaml
replicas:
  - name: zeiterfassung
    count: 3
images:
  - name: zeiterfassung
    newName: registry.hfi.local/saii/zeiterfassung
    newTag: "1.0"
patches:
  - path: deployment-prod.yaml
    target:
      kind: Deployment
      name: zeiterfassung
