apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ze-dev
resources:
  - namespace.yaml
  - ../../base
replicas:
  - name: zeiterfassung
    count: 1
images:
  - name: zeiterfassung
    newTag: "1.0"
patches:
  - path: service-nodeport.yaml
    target:
      kind: Service
      name: zeiterfassung
